blank_issues_enabled: false
contact_links:
  - name: Questions and Help
    url: https://github.com/Robin-Sch/insulation-simulation/discussions/new?category=feature-requests
    about: This issue tracker is for bugs only, not general support questions. Please open a discussion if you have any question and/or need help.
  - name: 🚀 Feature Request
    url: https://github.com/Robin-Sch/insulation-simulation/discussions/new?category=feature-requests
    about: Remember to search for existing feature requests and "up-vote" any you like